<a href="https://colab.research.google.com/github/kpowerinfinity/LearnPytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
# prompt: print hello world in python

print('hello world')


hello world


In [5]:
my_list = [1,2,3,4,5]

In [6]:
print my_list

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-6-20dd8dc07cba>, line 1)

In [7]:
print(my_list)

[1, 2, 3, 4, 5]


In [8]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [10]:
np1 = np.random.rand(3,4)

In [11]:
np1

array([[0.28145364, 0.94662556, 0.44359956, 0.2606797 ],
       [0.84495497, 0.86225256, 0.95129232, 0.67034418],
       [0.92440419, 0.3903851 , 0.62105355, 0.70516759]])

In [12]:
np1.dtype()

TypeError: 'numpy.dtypes.Float64DType' object is not callable

In [13]:
np1.dtype

dtype('float64')

In [14]:
tensor_2d = torch.randn(3,4)

In [15]:
tensor_2d

tensor([[ 1.1816, -1.2767,  1.6122,  0.2367],
        [ 0.2089,  0.1517,  0.7988, -0.9302],
        [-1.5933,  0.1115, -1.9633,  0.1739]])

In [16]:
tensor_3d = torch.zeroes(2,3,4)

AttributeError: module 'torch' has no attribute 'zeroes'

In [17]:
tensor_3d = torch.zeros(2,3,4)

In [18]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
np_tensor = torch.tensor(np1)

In [20]:
np_tensor

tensor([[0.2815, 0.9466, 0.4436, 0.2607],
        [0.8450, 0.8623, 0.9513, 0.6703],
        [0.9244, 0.3904, 0.6211, 0.7052]], dtype=torch.float64)